import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :mnemo, MnemoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# The launcher needs the address the endpoint picked; see
# `Mnemo.Endpoint.Address`.
config :mnemo, publish_endpoint_address: true

# No `force_ssl`. This endpoint listens on loopback and is reached by a
# window on the same machine; there is no certificate and no https to
# redirect to. Keeping it would leave a host-based exclusion list as the
# only thing between the application and an unreachable interface.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
